export { ColetaDadosForm } from "./ColetaDadosForm";
export { AtivoForm } from "./AtivoForm";
export { ImportarCarteiraIA } from "./ImportarCarteiraIA";
export { PlanejamentoIFForm } from "./PlanejamentoIFForm";
export { ProtecaoSucessorioForm } from "./ProtecaoSucessorioForm";
export { ProtecaoForm } from "./ProtecaoForm";
export { FiscalForm } from "./FiscalForm";
export { SucessorioForm } from "./SucessorioForm";
export { FinancialPlanningPage } from "./FinancialPlanningPage";
export { FinancialPlanDashboard } from "./FinancialPlanDashboard";
export { FinancialPlanPrintAdvisor, FinancialPlanPrintClient } from "./FinancialPlanPrint";
