// ⚠️ ARQUIVO GERADO — não edite à mão.
// Fonte: src/data/ativos.csv · Gerar: node scripts/gerarCatalogoAtivos.mjs
//
// Tupla por ticker: [card, segmento, setor?]. O setor só existe para Exterior,
// onde o segmento é o tipo de instrumento (Stocks/REITs/ETF RV) e o setor
// original da lista ("Technology", "Residential") vira informação de apoio.

import type { CardId } from "./types";

export type EntradaCatalogo = readonly [card: CardId, segmento: string, setor?: string];

export const CATALOGO_ATIVOS: Readonly<Record<string, EntradaCatalogo>> = {
  "A1RE34": ["exterior", "REITs", "Office"],
  "A1VB34": ["exterior", "REITs", "Residential"],
  "AAPL": ["exterior", "Stocks", "Technology"],
  "AAPL34": ["exterior", "Stocks", "Technology"],
  "ABBV": ["exterior", "Stocks", "Healthcare"],
  "ABBV34": ["exterior", "Stocks", "Healthcare"],
  "ABCB4": ["acoes", "Bancos"],
  "ABEV3": ["acoes", "Bebidas"],
  "ADBE": ["exterior", "Stocks", "Technology"],
  "ADBE34": ["exterior", "Stocks", "Technology"],
  "AERI3": ["acoes", "Máquinas e Equipamentos"],
  "AFHI11": ["fiis", "Recebíveis"],
  "AGRO3": ["acoes", "Agronegócio"],
  "ALOS3": ["acoes", "Shopping"],
  "ALUG11": ["exterior", "ETF RV", "EUA Imobiliário"],
  "ALUP11": ["acoes", "Energia"],
  "ALZR11": ["fiis", "Híbrido"],
  "AMBP3": ["acoes", "Saneamento"],
  "AMH": ["exterior", "REITs", "Residential"],
  "AMOB3": ["acoes", "Automotivo"],
  "AMT": ["exterior", "REITs", "Infrastructure"],
  "AMZN": ["exterior", "Stocks", "Consumer Services"],
  "AMZO34": ["exterior", "Stocks", "Consumer Services"],
  "ARE": ["exterior", "REITs", "Office"],
  "ASML": ["exterior", "Stocks", "Semiconductor"],
  "ASML34": ["exterior", "Stocks", "Semiconductor"],
  "AUAU3": ["acoes", "Pet Shop"],
  "AURA33": ["acoes", "Materiais Básicos"],
  "AURE3": ["acoes", "Energia"],
  "AVB": ["exterior", "REITs", "Residential"],
  "AVGO": ["exterior", "Stocks", "Technology"],
  "AVGO34": ["exterior", "Stocks", "Technology"],
  "AXIA3": ["acoes", "Energia"],
  "AZZA3": ["acoes", "Varejo"],
  "B3SA3": ["acoes", "Bolsa de Valores"],
  "BAC": ["exterior", "Stocks", "Financial"],
  "BBAS3": ["acoes", "Bancos"],
  "BBDC4": ["acoes", "Bancos"],
  "BBFO11": ["fiis", "FOF"],
  "BBIG11": ["fiis", "Shopping"],
  "BBOV11": ["acoes", "ETF Brasil", "Índice Ibovespa"],
  "BBSE3": ["acoes", "Seguros"],
  "BEEF3": ["acoes", "Alimentos"],
  "BHIA3": ["acoes", "Varejo"],
  "BLAU3": ["acoes", "Medicamentos"],
  "BLMG11": ["fiis", "Galpões Log."],
  "BND": ["exterior", "ETF RF", "Renda Fixa EUA"],
  "BOAC34": ["exterior", "Stocks", "Financial"],
  "BOVA11": ["acoes", "ETF Brasil", "Índice Ibovespa"],
  "BPAC11": ["acoes", "Bancos"],
  "BRAP4": ["acoes", "Mineração"],
  "BRAV3": ["acoes", "Petróleo, Gás e Biocombustíveis"],
  "BRBI11": ["acoes", "Bancos"],
  "BRCO11": ["fiis", "Galpões Log."],
  "BRCR11": ["fiis", "Lajes Corp."],
  "BRKM5": ["acoes", "Químicos"],
  "BRSR6": ["acoes", "Bancos"],
  "BTAL11": ["fiis", "Agronegócio"],
  "BTLG11": ["fiis", "Galpões Log."],
  "C1CL34": ["exterior", "REITs", "Infrastructure"],
  "C1MG34": ["exterior", "Stocks", "Consumer Cyclical"],
  "CAML3": ["acoes", "Alimentos"],
  "CASH3": ["acoes", "Software"],
  "CCI": ["exterior", "REITs", "Infrastructure"],
  "CHVX34": ["exterior", "Stocks", "Energy"],
  "CMG": ["exterior", "Stocks", "Consumer Cyclical"],
  "CMIG4": ["acoes", "Energia"],
  "CMIN3": ["acoes", "Mineração"],
  "COCA34": ["exterior", "Stocks", "Consumer Defensive"],
  "COST": ["exterior", "Stocks", "Consumer Services"],
  "COWC34": ["exterior", "Stocks", "Consumer Services"],
  "CPFE3": ["acoes", "Energia"],
  "CPLE3": ["acoes", "Energia"],
  "CPSH11": ["fiis", "Shopping"],
  "CPTR11": ["fiis", "Fiagro"],
  "CPTS11": ["fiis", "Hedge Fund"],
  "CSAN3": ["acoes", "Petróleo, Gás e Biocombustíveis"],
  "CSMG3": ["acoes", "Saneamento"],
  "CSUD3": ["acoes", "Software"],
  "CVCB3": ["acoes", "Consumo Cíclico"],
  "CVX": ["exterior", "Stocks", "Energy"],
  "CXSE3": ["acoes", "Seguros"],
  "CYRE3": ["acoes", "Construção Civil"],
  "D1LR34": ["exterior", "REITs", "Data Center"],
  "DEVA11": ["fiis", "Recebíveis"],
  "DEXP3": ["acoes", "Químicos"],
  "DG": ["exterior", "Stocks", "Consumer Services"],
  "DGCO34": ["exterior", "Stocks", "Consumer Services"],
  "DIS": ["exterior", "Stocks", "Entertainment"],
  "DISB34": ["exterior", "Stocks", "Entertainment"],
  "DIVO11": ["acoes", "ETF Brasil", "ETF de empresas pagadoras de dividendos"],
  "DLR": ["exterior", "REITs", "Data Center"],
  "DMVF3": ["acoes", "Medicamentos"],
  "E1QR34": ["exterior", "REITs", "Residential"],
  "E1XR34": ["exterior", "REITs", "Self-Storage"],
  "E2LS34": ["exterior", "REITs", "Residential"],
  "EGIE3": ["acoes", "Energia"],
  "ELS": ["exterior", "REITs", "Residential"],
  "EQIX": ["exterior", "REITs", "Data Center"],
  "EQIX34": ["exterior", "REITs", "Data Center"],
  "EQR": ["exterior", "REITs", "Residential"],
  "EQTL3": ["acoes", "Energia"],
  "ERUS": ["exterior", "ETF RV", "Mercado Russo"],
  "EXR": ["exterior", "REITs", "Self-Storage"],
  "EXXO34": ["exterior", "Stocks", "Energy"],
  "EZTC3": ["acoes", "Construção Civil"],
  "FATN11": ["fiis", "Lajes Corp."],
  "FESA4": ["acoes", "Siderurgia"],
  "FIQE3": ["acoes", "Comunicações"],
  "FLMA11": ["fiis", "Híbrido"],
  "FLRY3": ["acoes", "Saúde"],
  "GAME11": ["fiis", "Recebíveis"],
  "GARE11": ["fiis", "Híbrido"],
  "GGBR4": ["acoes", "Siderurgia"],
  "GGRC11": ["fiis", "Híbrido"],
  "GMAT3": ["acoes", "Varejo Alimentício"],
  "GOAU4": ["acoes", "Siderurgia"],
  "GOGL34": ["exterior", "Stocks", "Communication Services"],
  "GOLD11": ["exterior", "ETF RV", "Metais Preciosos"],
  "GOOGL": ["exterior", "Stocks", "Communication Services"],
  "GPUS11": ["exterior", "ETF RV", "S&P500 EUA"],
  "GRND3": ["acoes", "Calçados"],
  "HABT11": ["fiis", "Recebíveis"],
  "HAPV3": ["acoes", "Seguros"],
  "HASH11": ["cripto", "ETF Cripto", "Criptomoeda"],
  "HCTR11": ["fiis", "Recebíveis"],
  "HD": ["exterior", "Stocks", "Consumer Services"],
  "HFOF11": ["fiis", "FOF"],
  "HGBS11": ["fiis", "Shopping"],
  "HGCR11": ["fiis", "Recebíveis"],
  "HGLG11": ["fiis", "Galpões Log."],
  "HGRE11": ["fiis", "Lajes Corp."],
  "HGRU11": ["fiis", "Híbrido"],
  "HODL": ["cripto", "ETF Cripto", "Criptomoedas"],
  "HODL11": ["cripto", "ETF Cripto", "Criptomoedas"],
  "HOFC11": ["fiis", "Lajes Corp."],
  "HOME34": ["exterior", "Stocks", "Consumer Services"],
  "HSLG11": ["fiis", "Galpões Log."],
  "HSML11": ["fiis", "Shopping"],
  "HYPE3": ["acoes", "Medicamentos"],
  "IAU": ["exterior", "ETF RV", "Metais Preciosos"],
  "IBIT": ["cripto", "ETF Cripto", "Criptomoeda"],
  "IJJ": ["exterior", "ETF RV", "EUA Mid-Cap Valor"],
  "IJS": ["exterior", "ETF RV", "EUA Small-Cap Valor"],
  "INBR32": ["acoes", "Bancos"],
  "INTB3": ["acoes", "Produtos Diversos"],
  "INTC": ["exterior", "Stocks", "Technology"],
  "IRDM11": ["fiis", "Recebíveis"],
  "IRIM11": ["fiis", "Hedge Fund"],
  "ISAE4": ["acoes", "Energia"],
  "ITLC34": ["exterior", "Stocks", "Technology"],
  "ITRI11": ["fiis", "Hedge Fund"],
  "ITSA4": ["acoes", "Financeiro"],
  "ITUB4": ["acoes", "Bancos"],
  "IVOV": ["exterior", "ETF RV", "EUA Small-Cap Valor"],
  "IVVB11": ["exterior", "ETF RV", "S&P500 EUA"],
  "JBSS3": ["acoes", "Alimentos"],
  "JBSS32": ["acoes", "Alimentos"],
  "JHSF3": ["acoes", "Construção Civil"],
  "JNJ": ["exterior", "Stocks", "Healthcare"],
  "JNJB34": ["exterior", "Stocks", "Healthcare"],
  "JPM": ["exterior", "Stocks", "Financial"],
  "JPMC34": ["exterior", "Stocks", "Financial"],
  "JSLG3": ["acoes", "Bens Industriais"],
  "JSRE11": ["fiis", "Híbrido"],
  "JURO11": ["fiis", "FI-Infra"],
  "KEPL3": ["acoes", "Máquinas e Equipamentos"],
  "KISU11": ["fiis", "FOF"],
  "KLBN11": ["acoes", "Papel e Celulose"],
  "KLBN4": ["acoes", "Papel e Celulose"],
  "KNCA11": ["fiis", "Fiagro"],
  "KNCR11": ["fiis", "Recebíveis"],
  "KNRI11": ["fiis", "Híbrido"],
  "KNSC11": ["fiis", "Recebíveis"],
  "KNUQ11": ["fiis", "Recebíveis"],
  "KO": ["exterior", "Stocks", "Consumer Defensive"],
  "KORE11": ["fiis", "Lajes Corp."],
  "LEVE3": ["acoes", "Automotivo"],
  "LILY34": ["exterior", "Stocks", "Health Care"],
  "LLY": ["exterior", "Stocks", "Health Care"],
  "LOGG3": ["acoes", "Exploração de Imóveis"],
  "LREN3": ["acoes", "Varejo"],
  "LVBI11": ["fiis", "Galpões Log."],
  "M1NS34": ["exterior", "Stocks", "Consumer Defensive"],
  "M1TA34": ["exterior", "Stocks", "Communication Services"],
  "MA": ["exterior", "Stocks", "Transaction & Payment Processing Services"],
  "MATD3": ["acoes", "Saúde"],
  "MBRF3": ["acoes", "Alimentos"],
  "MCCI11": ["fiis", "Recebíveis"],
  "MCD": ["exterior", "Stocks", "Consumer Cyclical"],
  "MCDC34": ["exterior", "Stocks", "Consumer Cyclical"],
  "MCHI": ["exterior", "ETF RV", "China"],
  "MDIA3": ["acoes", "Alimentos"],
  "META": ["exterior", "Stocks", "Communication Services"],
  "MFII11": ["fiis", "Desenvolvimento"],
  "MGLU3": ["acoes", "Varejo"],
  "MILS3": ["acoes", "Locação - Máquinas e Equip."],
  "MMM": ["exterior", "Stocks", "Industrials"],
  "MMMC34": ["exterior", "Stocks", "Industrials"],
  "MNST": ["exterior", "Stocks", "Consumer Defensive"],
  "MOVI3": ["acoes", "Locação de Veículos"],
  "MRFG3": ["acoes", "Alimentos"],
  "MSCD34": ["exterior", "Stocks", "Transaction & Payment Processing Services"],
  "MSFT": ["exterior", "Stocks", "Technology"],
  "MSFT34": ["exterior", "Stocks", "Technology"],
  "MU": ["exterior", "Stocks", "Technology"],
  "MULT3": ["acoes", "Shopping"],
  "MUTC34": ["exterior", "Stocks", "Technology"],
  "MXRF11": ["fiis", "Recebíveis"],
  "MYPK3": ["acoes", "Automotivo"],
  "NASD11": ["exterior", "ETF RV", "EUA Tecnologia"],
  "NATU3": ["acoes", "Produtos de Uso Pessoal"],
  "NEOE3": ["acoes", "Energia"],
  "NFLX": ["exterior", "Stocks", "Entertainment"],
  "NFLX34": ["exterior", "Stocks", "Entertainment"],
  "NGRD3": ["acoes", "Software"],
  "NIKE34": ["exterior", "Stocks", "Consumer Cyclical"],
  "NKE": ["exterior", "Stocks", "Consumer Cyclical"],
  "NNN": ["exterior", "REITs", "Retail"],
  "NTCO3": ["acoes", "Produtos de Uso Pessoal"],
  "NU": ["acoes", "Bancos"],
  "NVDA": ["exterior", "Stocks", "Technology"],
  "NVDC34": ["exterior", "Stocks", "Technology"],
  "O": ["exterior", "REITs", "Retail"],
  "ODPV3": ["acoes", "Saúde"],
  "ORCL": ["exterior", "Stocks", "Information Technology"],
  "ORCL34": ["exterior", "Stocks", "Information Technology"],
  "P1LD34": ["exterior", "REITs", "Industrial"],
  "P1SA34": ["exterior", "REITs", "Self-Storage"],
  "P2LT34": ["exterior", "Stocks", "Information Technology"],
  "PASS3": ["acoes", "Gás"],
  "PCAR3": ["acoes", "Varejo"],
  "PCIP11": ["fiis", "Recebíveis"],
  "PEP": ["exterior", "Stocks", "Consumer Defensive"],
  "PEPB34": ["exterior", "Stocks", "Consumer Defensive"],
  "PETR4": ["acoes", "Petróleo, Gás e Biocombustíveis"],
  "PETZ3": ["acoes", "Pet Shop"],
  "PG": ["exterior", "Stocks", "Household & Personal Products"],
  "PGCO34": ["exterior", "Stocks", "Household & Personal Products"],
  "PLD": ["exterior", "REITs", "Industrial"],
  "PLPL3": ["acoes", "Construção Civil"],
  "PLTR": ["exterior", "Stocks", "Information Technology"],
  "PMLL11": ["fiis", "Shopping"],
  "PNVL3": ["acoes", "Medicamentos"],
  "PORD11": ["fiis", "Recebíveis"],
  "PRIO3": ["acoes", "Petróleo, Gás e Biocombustíveis"],
  "PSA": ["exterior", "REITs", "Self-Storage"],
  "PSEC11": ["fiis", "FOF"],
  "PSSA3": ["acoes", "Seguros"],
  "PVBI11": ["fiis", "Lajes Corp."],
  "QQQ": ["exterior", "ETF RV", "EUA Tecnologia"],
  "QQQM": ["exterior", "ETF RV", "EUA Tecnologia"],
  "QUAL3": ["acoes", "Seguros"],
  "R1IN34": ["exterior", "REITs", "Retail"],
  "RADL3": ["acoes", "Medicamentos"],
  "RAIL3": ["acoes", "Logística"],
  "RAIZ4": ["acoes", "Petróleo, Gás e Biocombustíveis"],
  "RANI3": ["acoes", "Papel e Celulose"],
  "RBRF11": ["fiis", "FOF"],
  "RBRP11": ["fiis", "Híbrido"],
  "RBRR11": ["fiis", "Recebíveis"],
  "RBRX11": ["fiis", "Hedge Fund"],
  "RBRY11": ["fiis", "Recebíveis"],
  "RBVA11": ["fiis", "Híbrido"],
  "RCRB11": ["fiis", "Lajes Corp."],
  "RDOR3": ["acoes", "Saúde"],
  "RECR11": ["fiis", "Recebíveis"],
  "RECT11": ["fiis", "Lajes Corp."],
  "RECV3": ["acoes", "Petróleo, Gás e Biocombustíveis"],
  "RELG11": ["fiis", "Galpões Log."],
  "RENT3": ["acoes", "Locação de Veículos"],
  "ROMI3": ["acoes", "Máquinas e Equipamentos"],
  "ROXO34": ["acoes", "Bancos"],
  "RSP": ["exterior", "ETF RV", "S&P500 EUA"],
  "RURA11": ["fiis", "Fiagro"],
  "RVBI11": ["fiis", "FOF"],
  "RZAG11": ["fiis", "Fiagro"],
  "RZAK11": ["fiis", "Recebíveis"],
  "RZTR11": ["fiis", "Agronegócio"],
  "S1LG34": ["exterior", "REITs", "Office"],
  "S2TA34": ["exterior", "REITs", "Industrial"],
  "SANB11": ["acoes", "Bancos"],
  "SAPR11": ["acoes", "Saneamento"],
  "SAPR4": ["acoes", "Saneamento"],
  "SAUD3": ["acoes", "Saúde"],
  "SBUB34": ["exterior", "Stocks", "Consumer Cyclical"],
  "SBUX": ["exterior", "Stocks", "Consumer Cyclical"],
  "SCHH": ["exterior", "ETF RV", "EUA Imobiliário"],
  "SEER3": ["acoes", "Educação"],
  "SEQR11": ["fiis", "Híbrido"],
  "SGOV": ["exterior", "ETF RF", "Renda Fixa EUA"],
  "SHUL4": ["acoes", "Automotivo"],
  "SIMH3": ["acoes", "Holding"],
  "SIMN34": ["exterior", "REITs", "Retail"],
  "SLCE3": ["acoes", "Agronegócio"],
  "SLG": ["exterior", "REITs", "Office"],
  "SMAC11": ["acoes", "ETF Brasil", "ETF de Small Caps brasileiras"],
  "SMAL11": ["acoes", "ETF Brasil", "ETF de Small Caps brasileiras"],
  "SMFT3": ["acoes", "Academias"],
  "SNAG11": ["fiis", "Fiagro"],
  "SNCI11": ["fiis", "Recebíveis"],
  "SOJA3": ["acoes", "Agronegócio"],
  "SPG": ["exterior", "REITs", "Retail"],
  "SPXB11": ["exterior", "ETF RV", "S&P500 EUA"],
  "SPY": ["exterior", "ETF RV", "S&P500 EUA"],
  "STAG": ["exterior", "REITs", "Industrial"],
  "SUZB3": ["acoes", "Papel e Celulose"],
  "SVAL11": ["exterior", "ETF RV", "EUA Small-Cap Valor"],
  "T1OW34": ["exterior", "REITs", "Infrastructure"],
  "TAEE11": ["acoes", "Energia"],
  "TASA4": ["acoes", "Armas e Munições"],
  "TECK11": ["exterior", "ETF RV", "Maiores empresas TECHs do mundo"],
  "TEPP11": ["fiis", "Lajes Corp."],
  "TFLO": ["exterior", "ETF RF", "Renda Fixa EUA"],
  "TGAR11": ["fiis", "Híbrido"],
  "TGMA3": ["acoes", "Logística"],
  "TIMS3": ["acoes", "Comunicações"],
  "TORD11": ["fiis", "Híbrido"],
  "TOTS3": ["acoes", "Software"],
  "TRBL11": ["fiis", "Galpões Log."],
  "TRIS3": ["acoes", "Construção Civil"],
  "TRXF11": ["fiis", "Híbrido"],
  "TRXY11": ["fiis", "Hedge Fund"],
  "TSLA": ["exterior", "Stocks", "Consumer Discretionary"],
  "TSLA34": ["exterior", "Stocks", "Consumer Discretionary"],
  "TSM": ["exterior", "Stocks", "Technology"],
  "TSMC34": ["exterior", "Stocks", "Technology"],
  "TTEN3": ["acoes", "Agronegócio"],
  "TUPY3": ["acoes", "Automotivo"],
  "TVRI11": ["fiis", "Híbrido"],
  "UL": ["exterior", "Stocks", "Household & Personal Products"],
  "ULEV34": ["exterior", "Stocks", "Household & Personal Products"],
  "UNIP6": ["acoes", "Químicos"],
  "URPR11": ["fiis", "Recebíveis"],
  "USDB11": ["exterior", "ETF RF", "Renda Fixa EUA"],
  "USIM5": ["acoes", "Siderurgia"],
  "V": ["exterior", "Stocks", "Transaction & Payment Processing Services"],
  "VALE3": ["acoes", "Mineração"],
  "VAMO3": ["acoes", "Locação de Veículos"],
  "VBBR3": ["acoes", "Petróleo, Gás e Biocombustíveis"],
  "VEA": ["exterior", "ETF RV", "Países Desenvolvidos Excluído EUA"],
  "VGHF11": ["fiis", "Hedge Fund"],
  "VGIA11": ["fiis", "Fiagro"],
  "VGIP11": ["fiis", "Recebíveis"],
  "VGIR11": ["fiis", "Recebíveis"],
  "VICI": ["exterior", "REITs", "Casino"],
  "VILG11": ["fiis", "Galpões Log."],
  "VINO11": ["fiis", "Lajes Corp."],
  "VIOV": ["exterior", "ETF RV", "EUA Mid-Cap Valor"],
  "VISA34": ["exterior", "Stocks", "Transaction & Payment Processing Services"],
  "VISC11": ["fiis", "Shopping"],
  "VIUR11": ["fiis", "Híbrido"],
  "VIVA3": ["acoes", "Varejo"],
  "VIVT3": ["acoes", "Comunicações"],
  "VNQ": ["exterior", "ETF RV", "EUA Imobiliário"],
  "VNQI": ["exterior", "ETF RV", "Imobiliário Global Excluído EUA"],
  "VOO": ["exterior", "ETF RV", "S&P500 EUA"],
  "VPPR11": ["fiis", "Lajes Corp."],
  "VRTA11": ["fiis", "Recebíveis"],
  "VSLH11": ["fiis", "Recebíveis"],
  "VT": ["exterior", "ETF RV", "Mundo"],
  "VUAA": ["exterior", "ETF RV", "S&P500 EUA"],
  "VULC3": ["acoes", "Calçados"],
  "VWO": ["exterior", "ETF RV", "Mercados Emergentes"],
  "VXUS": ["exterior", "ETF RV", "Mercado Internacional Ex EUA"],
  "W1EL34": ["exterior", "REITs", "Healthcare"],
  "WALM34": ["exterior", "Stocks", "Consumer Services"],
  "WEGE3": ["acoes", "Motores e Compressores"],
  "WELL": ["exterior", "REITs", "Healthcare"],
  "WIZC3": ["acoes", "Seguros"],
  "WMT": ["exterior", "Stocks", "Consumer Services"],
  "WRLD11": ["exterior", "ETF RV", "Mundo"],
  "XINA11": ["exterior", "ETF RV", "China"],
  "XLRE": ["exterior", "ETF RV", "EUA Imobiliário"],
  "XOM": ["exterior", "Stocks", "Energy"],
  "XP": ["acoes", "Financeiro"],
  "XPBR31": ["acoes", "Financeiro"],
  "XPIN11": ["fiis", "Galpões Industriais"],
  "XPLG11": ["fiis", "Galpões Log."],
  "XPML11": ["fiis", "Shopping"],
  "XPPR11": ["fiis", "Lajes Corp."],
};

export const CATALOGO_TOTAL = 381;
